spring:
  application:
    name: route_nxt_service
  datasource:
    url: jdbc:mysql://localhost:3306/route_nxt?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 9906170779189830
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
